AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: weather_api_demo 

Resources:

  WeatherDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false

  WeatherReadFrontendFunction:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: weather_read_frontend/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api 
          Properties:
            Path: /weather
            Method: GET
      Environment: 
        Variables:
          DYNAMO_TABLE: !Ref WeatherDynamoTable
      Policies: 
        - DynamoDBReadPolicy:
            TableName: !Ref WeatherDynamoTable

  WeatherDataGeneratorFunction:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: weather_data_generator/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        Clock:
          Type:  ScheduleV2
          Properties:
            ScheduleExpression: rate(1 minute)
      Environment: 
        Variables:
          DYNAMO_TABLE: !Ref WeatherDynamoTable
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref WeatherDynamoTable

Outputs:
  WeatherDynamoTableName:
    Value: !Ref WeatherDynamoTable

  WeatherDynamoTableNameArn :
    Value: !GetAtt WeatherDynamoTable.Arn

  WeatherAPI:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/weather/"

